# Generated by Django 4.2.2 on 2023-12-13 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_usuario_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='user',
        ),
    ]
