# Generated by Django 5.0 on 2023-12-13 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_remove_usuario_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='descripcion',
            new_name='fechayhora',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='nombre_usuario',
            new_name='nombre_doc',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='ID_usuario',
            new_name='nombre_paciente',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='img',
        ),
    ]
